
from core.version import (AIL_VERSION, AIL_VERSION_STATE,
                          AIL_SUB_VERSION, AIL_MAIN_VERSION)

_IS_AIL_MODULE_ = True

_AIL_NAMESPACE_ = {
    'AIL_MAIN_VERSION': AIL_MAIN_VERSION,
    'AIL_SUB_VERSION': AIL_SUB_VERSION,
    'AIL_VERSION': AIL_VERSION,
    'AIL_VERSION_STATE': AIL_VERSION_STATE,
}
