

ATTRIBUTE_ERROR = 'AttributeError'
TYPE_ERROR = 'TypeError'
PYTHON_RUNTIME_ERROR = 'PythonRuntimeError'
PYTHON_ERROR = 'PythonError'
UNHASHABLE_ERROR = 'UnhashableError'
INDEX_ERROR = 'IndexError'
OBJECT_ERROR = 'ObjectError'
OS_ERROR = 'OSError'
LOAD_ERROR = 'LoadError'
IMPORT_ERROR = 'ImportError'
RECURSION_ERROR = 'RecursionError'
VM_ERROR = 'VMError'
NAME_ERROR = 'NameError'
ZERO_DIVISION_ERROR = 'ZeroDivisionError'
KEY_ERROR = 'KeyError'
UNICODE_DECODE_ERROR = 'UnicodeDecodeError'
UNICODE_ENCODE_ERROR = 'UnicodeEncodeError'
FILE_NOT_FOUND_ERROR = 'FileNotFoundError'
